import img1 from "../../images/calipers.png";
import img2 from "../../images/calipers2.png";

export const details = [
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "wheels",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "rims",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "headlight",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "fog lamps",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
  {
    img1: img1,
    img2: img2,
    name: "yellow callipers",
    pricing: "₹54000",
    cutpricing: "₹90000",
    link: "/",
  },
];
